name: compas_slicer
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  # core
  - attrs>=21.0
  - compas>=2.0
  - compas_cgal>=0.8
  - networkx>=3.0
  - numba>=0.58
  - numpy>=1.24
  - progressbar2>=4.0
  - pyclipper>=1.3
  - rdp>=0.8
  - scipy>=1.10
  # dev
  - invoke>=2.0
  - pytest>=7.0
  - pytest-cov
  - ruff
  - mypy
  - sphinx>=6.0
  - sphinx_compas_theme>=0.24
  - nbsphinx
  - ipykernel
  - ipython>=8.0
  - twine
  - pip:
    - bump2version>=1.0
    - -e .
