name: compas_slicer
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  # core
  - attrs>=25.0
  - compas>=2.15
  - compas_cgal>=0.9
  - networkx>=3.6
  - numpy>=2.0
  - progressbar2>=4.5
  - pyclipper>=1.4
  - rdp>=0.8
  - scipy>=1.16
  # viz
  - compas_viewer>=1.2
  # dev
  - invoke>=2.0
  - pytest>=7.0
  - pytest-cov
  - ruff
  - mypy
  - sphinx>=6.0
  - sphinx_compas_theme>=0.24
  - nbsphinx
  - ipykernel
  - ipython>=8.0
  - twine
  - pip:
    - bump2version>=1.0
    - -e .
